# Generated by Django 4.1.1 on 2022-09-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bonus',
            field=models.IntegerField(default=1),
        ),
    ]
